# Generated by Django 5.2 on 2025-04-15 18:31

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='entrenador',
            name='apellido',
            field=models.CharField(default=builtins.dir, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entrenador',
            name='especialidad',
            field=models.CharField(choices=[('halterofilia', 'Halterofilia'), ('gimnasio', 'Gimnasio'), ('metcon', 'Metcon')], max_length=20),
        ),
    ]
