# Generated by Django 5.2 on 2025-04-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0004_biblioteca'),
    ]

    operations = [
        migrations.AddField(
            model_name='atleta',
            name='plan',
            field=models.IntegerField(choices=[(0, '8 Clases'), (1, '12 Clases'), (2, '16 Clases'), (3, 'Open Box'), (4, 'Full Clases')], default=0),
            preserve_default=False,
        ),
    ]
