# Generated by Django 5.2 on 2025-04-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0005_atleta_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biblioteca',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
